spring.application.name=library
server.port=8080

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/librarydb}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

logging.level.root=INFO
logging.level.com.lab11.library=DEBUG
logging.file.name=logs/library-app.log

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

app.jwt.secret=${JWT_SECRET:RuslanJulayevSuperSecretJwtKeyForFinalProjectChangeMe123456789}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}
